### PR TITLE
Fix routes for CSV

### LINKED ISSUE #117: CSV download links don't work if the rails root is set
Use the route helper for csv links or use `ENV['RAILS_RELATIVE_URL_ROOT'] + '/csv/book_chapters.csv'`

### PR DESCRIPTION
**Pull request by bsp3ars**
Fixes #117 

Implements a helper method that should fix the server issues when making links.

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -15,4 +15,12 @@ def shorten_long(input)
     end
     return_string
   end
+
+  def csv_route(type)
+    if ENV['RAILS_RELATIVE_URL_ROOT'].nil?
+      "/csv/#{type}.csv"
+    else
+      ENV['RAILS_RELATIVE_URL_ROOT'] + "csv/#{type}.csv"
```
Comment (hortongn) [inline app/helpers/application_helper.rb:23]: in your else statement you do still need the "/" at the beginning of the string.  The variable will contain "/aaec" so the string will need to be "/csv/#{type}.csv"

Also a slicker way of doing this without a conditional is just to use `ENV['RAILS_RELATIVE_URL_ROOT'].to_s + "/csv/#{type}.csv"`.  If the variable is `nil` the `.to_s` will convert it to an empty string.

**Comment by hortongn** [comment]
@bsp3ars You didn't make my suggested change.  Nothing changed in your latest commit.

**Comment by bsp3ars** [comment]
@hortongn Sorry it didn't get committed properly. It should be good now
