### PR TITLE
249 - Fix invalid access token error

### LINKED ISSUE #249: ActionController::InvalidAuthenticityToken in SubmittersController#create
### The app crashes upon creating new submitter after logging out and using back arrows to get to submitter creation page.  Reproducible
Steps to recreate:

1. start the app at localhost:3000
2. create a submitter, hit submit
3. create a work
4. click "I'm finished"
5. use the back arrows to navigate back to the page where you created your submitter
6. notice that the form is pre-filled with your old information.  
7. click "submit" on the submitter creation page where your old information shows
8. App crashes:

Screenshot 2023-10-13 at 9 27 25 PM

The same process and results happen with the admin login.

I suggest using begin/rescue blocks to gracefully handle this and redirect the user to a fresh login page.

### PR DESCRIPTION
**Pull request by Janell-Huyck**
Fixes #249 

This PR creates another controller "concern", ExceptionHandlingManager, to take care of the InvalidAuthenticityToken error and to collect other custom error handling created in the future.  

It is called inside the application_controller and does the following:
- logs a warn-level message
- resets the session (logs out old users)
- redirects the user to the root_page or manage_page as appropriate, with a flash warning message

### Tests:
- Unit tests: spec/controllers/concerns/exception_handling_manager_spec.rb

- Feature tests: I created a series of tests to address how the application should or should not be able to be accessed in combinations of the following issues:
  - The app is out of date
  - The user has an invalid authenticity token
  - The user isn't logged in
  
  This series of tests is why I marked this PR as "large".  They are in the folder: spec/features/application_access/

### Additional changes
- Resets the session upon successfully logging in as an admin (to prevent session fixation attacks).  This incidentally fixes the bug that allowed a user to log in as both an admin and a submitter at the same time.
- Skips user validation for "closed" and "finished" pages to avoid an infinite looping bug encountered while testing
- Clarifies a few lines in submitters_controller_spec

### CODE REVIEW

File: spec/rails_helper.rb [hunk 1]
```diff
@@ -77,6 +77,8 @@
 
 def create_submitter(submitter)
```
Comment (crowesn) [inline spec/rails_helper.rb:78]: Not directly related to this PR, but wondering if this function might find a better home in /spec/support.

**Review by crowesn — APPROVED** [review]
This is a dense PR, good work, merging.
